### ISSUE TITLE
Add layout templates to re-use complete card designs

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#119]
## The Problem To Be Solved
Currently, all sorts of templates are supported to enable the re-use of tools, toolsets, colors, JavaScript snippets, etc.

However, if one wants to use the created cards in views, it is still a lot of YAML, as you have to declare the full card layout: there are no layout templates available. Ie no re-use of cards like you can with the decluttering templates and the button card.

### Additional background:
Usability for many users will be improved significantly with layout templates! Of course, these templates should support variables, as this greatly enhances the use of templates.

The usage of the functional card examples for instance could benefit from this!

## (Optional): Suggested Solution
Layout templates should be consistent with existing templates.

Example:
```yaml
       - type: 'custom:swiss-army-knife-card'
          entities:
            - entity: sensor.dsmr_reading_electricity_currently_delivered
              name: 'Sensor #2'
          layout:
            template:
              name: sak_layout_fce_sensor2
              variables:
                - sak_layout_sensor_segarc_scale_max: 2
```
## Included in this feature
Apart from the software changes, the following changes are part of this feature request:
- Rework all the functional card examples to use layout templates
- Rework the documentation (of course)

Tentative:
- Rework all the existing 12 examples to use layout templates
- Rework the documentation (of course)
