### ISSUE TITLE
Add animations to tools

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#13]
## The Problem To Be Solved
The horse shoe contains animations: if an entity changes from state, you can run an animation on some of the objects (icon, lines circles) using default css animation functionality. This can be defined in the card yaml.

The idea is to implement animations on the swiss army knife also!

The horse shoe implementation  looks like this:
```yaml
animations:
  entity.1:
    - state: 'on'
    circles:
      - animation_id: 10
      styles:
        - fill: var(--theme-gradient-color-08);
        - opacity: 0.9;
        - animation: jello 1s ease-in-out both;
        - transform-origin: center;
    icons:
      - animation_id: 0
      styles:
        - fill: black;
    - state: 'off'
    circles:
      - animation_id: 10
      reuse: true
      styles:
        - transform-origin: center;
        - animation: zoomOut 1s ease-out both;
    icons:
      - animation_id: 0
      styles:
        - fill: var(--primary-text-color);

```
The objects look like this:
```yaml
icons:
  - id: 0
    animation_id: 0
    xpos: 50
    ypos: 55
    entity_index: 1
    icon_size: 3.5
    styles:
      - color: white;
circles:
  - id: 0
    animation_id: 0
    xpos: 50
    ypos: 50
    radius: 35
    styles:
      - fill: var(--primary-background-color);
  - id: 1
    animation_id: 10
    xpos: 50
    ypos: 50
    radius: 30
    entity_index: 1
    styles:
      - fill: var(--primary-background-color);

```
You can see how the objects, animations, and entities are linked together:
- objects linked to entities using entity_index (index in entities list)
- objects linked to animation using separate animation_id 

So:
- a single entity can trigger multiple animations on several objects.
- an object is linked to a **single** animation! This avoids weird behavior / race conditions / etc.

### 1:1 implementation
The sak card uses separate tool objects for each object: the idea is that each object itself handles operations on the object. This means that animations should also be handled by the object/tool itself.

For this:
- tool knows the entity_index for which it is linked
- the animation is part of the tool config, hence local
- the value of that entity is automatically pushed to the tool using its `tool.value =` function.
- in the `.value` function, the tool can calculate the animation styles itself. These styles will be added to the styles used to redraw the tool during a render action initiated by a changed entity.

The animation config could look like this:
```yaml
type: "circle"
entity_index: 1
animations:
  - state: 'on'
    styles:
      - fill: var(--theme-gradient-color-08);
      - opacity: 0.9;
      - animation: jello 1s ease-in-out both;
      - transform-origin: center;
  - state: 'off'
    reuse: true
    styles:
      - transform-origin: center;
      - animation: zoomOut 1s ease-out both;
```
### Extensions
Not sure, but are things like state values already supported now:
```yaml
animations:
  - state: 40
    operator: '>'
    styles:
      - fill: var(--theme-gradient-color-08);
  - state: 20
    operator: '>'
    styles:
      - fill: var(--theme-gradient-color-01);
```
The default operators is '='
Evaluation stops after a match is found!

If this is extended for icons and text, these can change color depending on the state. Would be nice??
