### ISSUE TITLE
Extend templating with colors

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#14]
## The Problem To Be Solved
Templating tools makes re-use of toolsets possible. This already shortens the yaml files with a large amount.
It would be nice if the same can be done for colors (colorstops, colorlists)...

Of course, re-use is much better if global sak-templates are implemented, so re-use can take place over cards, instead of (currently) only within a card.

## (Optional): Suggested Solution
Example:
```yaml
templates:
  - type: tools
    name: tools-segarc-icon-state
    tools:
    
  - type: colorstops
    name: colorstops-lux
    colorstops:
      colors:
        0: 'grey'
        50: 'var(--theme-gradient-color-01)'
        75: 'var(--theme-gradient-color-02)'
        100: 'var(--theme-gradient-color-03)'
        125: 'var(--theme-gradient-color-04)'
        150: 'var(--theme-gradient-color-05)'
        175: 'var(--theme-gradient-color-06)'
  - type: colorstops
    name: colorstops-pressure
    colorstops:
      colors:
        980: 'lightgrey'
        990: 'var(--theme-gradient-color-01)'
        1020: 'var(--theme-gradient-color-05)'

```

And in the definition of the tool:
```yaml
- toolset: lux
  template: segarc-icon-state
  position:
    cx: 175
    cy: 50
    scale: 1
  variables:
    - entity: 3
    - show_scale: false
  tools:
    - type: segarc
      id: 0
      show:
        style: 'colorstops'
        scale: true
      scale:
        min: 0
        max: 200
      segments:
        colorstops:
          gap: 0
          # Can we use template colorstop lists? For easy re-use??
          template: colorstops-lux

```
