### ISSUE TITLE
Add min/max labels to bar tool

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#15]
## The Problem To Be Solved
The bar tool is actually a sparkline variant: it displays only the bar values, nothing more.
Adding min/max value labels (positioning is free) would add value to the chart.

## (Optional): Suggested Solution
Enabling min and max labels using a flag, or only their relative position.
Position is relative to center of chart. This makes it possible to move the chart, and keep the labels in place.

Assuming:
- chart is 80 wide
- chart is 40 high

min label at lower left corner:
- rx = -40 (is 80/2)
- ry = -25 (is 40/2) - 5. Meaning below the chart.

**Update @2020.11.10:**
The number of decimals is determined by the decimals value for the entity

Styling is done in the usual way: using a style.
For this, the styles section should be extended to be able to format the bar and the labels. Labels can be styled at once, or individually. This means that text-anchor can be set (start, middle, end), which might come in handy!
```yaml
  styles:
    bar:
      <values>
    label:
      <values>
    label_min:
      <values>
    label_max:
      <values>
    label_ave:
      <values>
```
etc.
