### ISSUE TITLE
Add labels to segmented arc tool

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#16]
## The Problem To Be Solved
The min/max values of the segmented arc are not displayed. It would be nice if this would be possible, of course free placement, and styling.
This could be extended with extra labels like 20%, or 50%.

## (Optional): Suggested Solution
Label positioning:

```yaml
show:
  labels: true

labels:
  min:
    rx: 0
    ry: -10
    style:
      fill: 'red'
  max:
    rx: 100
    ry: -10
  50:
    rx: 10
    ry: 20
    value: 'Half way'
  highpres:
    rx: -10
    ry: 10
    value: 'High Pressure'

```
