### ISSUE TITLE
Circular Slider Tool acts weird with "odd" scales

### ISSUE THREAD

**Issue by KingCruzIII** [AmoebeLabs/swiss-army-knife-card#172]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [ x] Yes, I'm sure that it is not a configuration mistake

## Bug description
When using "odd" scales the tool acts jittery, wont slide past a certain point, or will only bottom/max out.
Example:
```
  min: 60
  max: 70
  step: 1
```
will make it only make it want to be 60 or 70.
  
```
  min: 50
  max: 70
  step: 1
```
it wont to below 60

Varous other sets of min/max will also have similar effects.
70/100
15/25

But there are still some that work like you would think
14/24
50/90

### To Reproduce
```
  - path: circslider
    title: circslider test
    cards:
      - type: "custom:swiss-army-knife-card"
        entities:
          - entity: climate.thermostat
            attribute: temperature
        aspectratio: 1/1
        layout:
          toolsets:
            # ================================================================
            - toolset: circ-slider-test 
              position:
                cx: 50
                cy: 50
              tools:
                # ------------------------------------------------------------
                - type: circslider
                  position:
                    cx: 50
                    cy: 40
                    radius: 25
                    start_angle: -90
                    end_angle: 90
                    thumb:
                      width: 4
                      height: 4
                    label:
                      placement: "position"
                      cx: 50
                      cy: 50
                  entity_index: 0
                  scale:
                    min: 60
                    max: 70
                    step: 1
                  styles:
                    active:
                      stroke: var(--accent-color)
                      stroke-width: 2em
                      stroke-linecap: round
                    track:
                      stroke: var(--secondary-text-color)
                      fill-opacity: 1
                      stroke-width: 2em
                      stroke-linecap: round
                    thumb:
                      fill: var(--accent-color)
                    capture:
                      fill: none
                    label:
                      text-anchor: middle
                      font-size: 25em
                      font-weight: 500
                      fill: var(--primary-text-color)
```
### Expected behavior
I would expect that you could set any min/max ratio and the slider would not be jittery.

### Screenshots
![circslider](https://user-images.githubusercontent.com/18471324/200154150-dfb97b74-e612-4b9a-96cd-f19d6a9c418c.gif)
![circslider2](https://user-images.githubusercontent.com/18471324/200154153-d116c2e4-e055-4099-9542-e003a0632f97.gif)

### Desktop browser (please complete the following information):
 - OS: Windows
 - Browser chrome
 - Version 107.0.5304.88

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: Galaxy S20+
 - OS: Android
