### ISSUE TITLE
Make tool styles and animation styles consistent

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#19]
Using a map and array. Should be map. Why is an array used??
```yaml
animations:
  - state: 'on'
    styles:
      - fill: var(--theme-gradient-color-08);
      - opacity: 0.9;
  - state: 'off'
    reuse: true
    styles:
      - fill: var(--theme-gradient-color-01);
      - opacity: 0.7;
styles:
  font-size: 1.5em;
  text-anchor: start;
```
