### ISSUE TITLE
Icon (ok) and segmented arc (nok) not showing the same color at exact colorstop limits

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#191]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [x] Yes, I'm sure that it is not a configuration mistake

## Bug description

The colorstop limits are nog always consistent between segmented arc and animations.
The segmented arc stays green when percentage changes to 40% (why??), but after a browser refresh it becomes yellow. The battery percentage icon however stays green at 40%.

Both are using the same colorstop template. So this seems some calculation is going wrong to determine the current color in the `segarc` rendering after a refresh. Might be something about > or >= or < and <=.

Battery percentage at 40%:
![image](https://user-images.githubusercontent.com/7996307/235436317-1226199e-bca9-4936-aa98-82b3b9e89032.png)

And battery percentage at 39%:
![image](https://user-images.githubusercontent.com/7996307/235436466-2ad07d13-e19a-4ade-bed5-eef71390608c.png)

### To Reproduce

YAML definition of view part:
```yaml
          layout:
            template:
              name: sak_layout_fce_sensor2
              variables:
                - sak_layout_sensor_colorstops_template: colorstops_battery_level
                - sak_layout_sensor_icon_style: colorstops
                - sak_layout_sensor_segarc_style: colorstops
                - sak_layout_sensor_scale_max: 100    
```

The `colorstops_battery_level` template looks like this:
```yaml
colorstops_battery_level:
  template:
    type: colorstops
    defaults:
      - thegap: 1
      - theFill: true
      - theStroke: false
  colorstops:
    gap: '[[thegap]]'
    fill: '[[theFill]]'
    stroke: '[[theStroke]]'
    colors:
      00: 'var(--brand-google-red)'
      20: 'var(--brand-google-yellow)'
      40: 'var(--brand-google-green)'
```

### Expected behavior

Both the `icon` as the `segarc` are using the same (of course) colorstop template, so should show the same colors. Even after a refresh!

### Desktop browser (please complete the following information):
 - OS: [e.g. Windows]
 - Version [e.g. 110]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [e.g. iPhone16]
 - OS: [e.g. iOS16]
 - Version [e.g. 16]

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.
