### ISSUE TITLE
'unavailable' state as a working state for animations etc

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#195]
## The Problem To Be Solved
When retrieving state,  the 'unavailable' one doesn't seem to be parsed to SAK. so animation state 'unavailable' can't be used.
![image](https://user-images.githubusercontent.com/51697064/235893655-14b7ef88-a27d-465f-ad0c-0595bee4d901.png)

this state is useful for displaying if there is a connection issue with an entity.

### Additional background:

tried both with and without ' ' 

```

        animations:
          - state: 'off'
            styles:
              rectex:
                fill: rgba(97, 69, 71, 1)
                transition: fill 0.5s linear
          - state: 'on'
            styles:
              rectex:
                fill: rgba(0,0,0,0)
                transition: fill 0.5s linear
          - state: 'unavailable'
            styles:
              rectex:
                fill: rgba(97, 69, 71, 1)
                transition: fill 0.5s linear
```

## (Optional): Suggested Solution

make 'unavailable' a working state

## current workaround i use is to use the is not operator:
```
        animations:
          - state: 'off'
            styles:
              rectex:
                fill: rgba(97, 69, 71, 1)
                transition: fill 0.5s linear
          - state: 'on'
            styles:
              rectex:
                fill: rgba(0,0,0,0)
                transition: fill 0.5s linear
          - state: 'on'
            operator: '!='
            styles:
              rectex:
                fill: rgba(97, 69, 71, 1)
                transition: fill 0.5s linear
```

example, my garage light has lost its connection to the zigbee network, now displayed in my card:
![image](https://user-images.githubusercontent.com/51697064/235894455-e8cb989d-5961-402b-918b-b65e30be727a.png)
