### ISSUE TITLE
Impossible to style usersvg.

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#196]
- [ ] No, I'm not sure that it is not a configuration mistake

## Bug description
Impossible to style usersvg. i hope there is no error in the code itself or that i'm overlooking something.
Things i tried:
had styling under animation first, but moved it inline to be able to test it better.
used following style 'options' 

usersvg
svg
image
toolsets

using both my own SVG as well as one of your built-in ones to be sure that its not a problem with the SVG itself.

### To Reproduce
Using this code:

    ```
          - type: 'custom:swiss-army-knife-card'
                aspectratio: 1/1
                entities:
                - entity: sensor.recycleapp_tomorrow
                - entity: sensor.recycleapp_today
                - entity: sensor.recycleapp_glas
                layout:
                  styles:
                    card:
                      background: rgba(97, 69, 71, 1)
                      border: none
                      box-shadow: none
                  toolsets:
                    - toolset: background
                      position:
                       cx: 50
                       cy: 50
                      tools:
                      - type: 'usersvg'
                        position:
                          cx: 50
                          cy: 50
                          height: 100
                          width: 100
                        images:
                          - default: /local/images/airvisual/ic-face-2.svg
                          - glas: /local/images/glas.svg
                        entity_indexes:
                          - entity_index: 2
                          - entity_index: 1
                          - entity_index: 0
                        animations:
                          - state: Tomorrow
                            image: glas
                        styles:
                          usersvg:
                            opacity: 0.5
```

### Expected behavior
have the svg change opacity (i want to do color or apply a filter, but opacity is in my opinion the most fool-proof way to test the styling is working.

### Screenshots
![image](https://user-images.githubusercontent.com/51697064/236676012-c7025d01-36d3-4885-8017-7fb29e2eecc2.png)
