### ISSUE TITLE
Support for custom popups in the actions configuration

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#203]
## The Problem To Be Solved
The current implementation supports the following user actions:
- more-info (popup)
- navigate (to other panel)
- call-service (to call a HA service such as switching lights)

Displaying a custom popup window is not possible.

### Additional background:
See: https://community.home-assistant.io/t/lovelace-versatile-swiss-army-knife-custom-card/432419/95

## (Optional): Suggested Solution
For now, check how other cards allow for custom popups, and check if this configuration can be re-used for consistency with other cards...

Most examples use the `browser_mod` extension to allow for custom popups using the `fire-dom-event` action and browser_mod configuration:
```yaml
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Some Popup
          content:
            type: entities
              - !include ../folder-with-popups/popup.yaml
```

The custom-card-helpers has this solution in https://github.com/custom-cards/custom-card-helpers/blob/master/src/handle-click.ts:
```javascript
    case "fire-dom-event": {
      fireEvent(node, "ll-custom", actionConfig);
      if (actionConfig.haptic) forwardHaptic(actionConfig.haptic);
      break;
```

`actionConfig` contains the full configuration of the action, so includes the `.action` field for instance.

Using browser_mod means support for `fire-dom-event` in the actions configuration and eventhandler in SAK, which is a combination of `handleTapEvent()` and `_processTrapEvent()`.

Looking from the other side: support for `fire-dom-event` means support for all the browser_mod callable functions, including notifications and more!
