### ISSUE TITLE
Action doesn't work with multiple entity indexes

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#207]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [x] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
The version you are using. See HACS or the Browser console
v2.4.2

## Bug description

See: https://community.home-assistant.io/t/lovelace-versatile-swiss-army-knife-custom-card/432419/161

### To Reproduce
- See below YAML definition.
- When multiple indexes are defined, the action is not executed, but an error is reported!

### Expected behavior
The action/tap handler should work as with a single entity.

### Screenshots

![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/99e3b45d-afb2-4e42-a28e-cd28f0cc36ba)

![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/3a4e1e04-fdb6-4824-8f81-61a3505cf6e1)

```yaml
- type: icon
            position:
              cx: 50
              cy: 50
              align: start
              icon_size: 20
            entity_indexes:
              - entity_index: 7     # Fan mode Quiet
              - entity_index: 6     # On/Off
            user_actions:
              tap_action:
                haptic: success
                actions:
                  - action: call-service
                    service: climate.set_fan_mode
                    service_data:
                      fan_mode: quiet
            animations:
              - state: "quiet"
                styles:
                  icon:
                    animation: spin 5s linear infinite
                    fill: var(--md-fg-color--alert)
                    color: var(--md-fg-color--alert)
              - state: "quiet"
                operator: '!=' 
                styles:
                  icon:
                    fill: gray 
              - state: "off"
                entity_index: 6
                styles:
                  icon:
                    fill: gray
```
### Desktop browser (please complete the following information):
 - OS: [e.g. Windows]
 - Version [e.g. 110]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [e.g. iPhone16]
 - OS: [e.g. iOS16]
 - Version [e.g. 16]

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.
