### ISSUE TITLE
Wrong Icon is displayed when using multiple entity indexes in animation

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#210]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [x] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
The version you are using. See HACS or the Browser console
v2.4.3

## Bug description
If more than 1 entity index is used in the animation section, the wrong icon is displayed. In most cases the icon from the secondary entity index.

### To Reproduce

Below:
- entity index 0 has face-man icon
- entity index 1 has fan icon

A light bulb icon is displayed however!

```yaml
        - type: 'custom:swiss-army-knife-card'
          entities:
            - entity: light.livingroom_light_duo_right_light
              name: 'CircSlider Test'
              icon: mdi:face-man
            - entity: light.livingroom_light_duo_right_light
              attribute: brightness
              unit: "%"
              format: brightness
              icon: mdi:fan

              - toolset: circ-slider-test
                position:
                  cx: 50
                  cy: 50
                tools:              
                  # ------------------------------------------------------------
                  - type: icon
                    position:
                      cx: 85
                      cy: 50
                      align: center
                      icon_size: 40
                    entity_indexes:
                      - entity_index: 1
                      - entity_index: 0
                    animations:
                      - state: 'on'
                        entity_index: 0
                        reuse: true
                        # icon: mdi:fan
                        styles:
                          icon:
                            fill: 'red'
                          tool:
                            display: initial
                      - state: 'off'
                        reuse: true
                        entity_index: 0
                        styles:
                          icon:
                            fill: 'blue'
```

### Expected behavior

A fan icon should be displayed, as configured.

### Desktop browser (please complete the following information):
 - OS: [e.g. Windows]
 - Version [e.g. 110]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [e.g. iPhone16]
 - OS: [e.g. iOS16]
 - Version [e.g. 16]

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.
