### ISSUE TITLE
Double SVG with usersvg.

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#214]
## Swiss Army Knife version
2.4.4

## Bug description
I think usersvg injects an SVG twice, noticed this when using style filter invert that it didnt work unless i switched the invert from 0 to 1 after page was loaded. also noticed SAK 'reshaping' the svg to the correct dimensions twice. 

### To Reproduce
Card code: 
```
                    type: 'custom:swiss-army-knife-card'
                    aspectratio: 1/1
                    entities:
                    - entity: sensor.recycleapp_pmd
                    layout:
                      styles:
                        card:
                          background: rgba(97, 69, 71, 1)
                          border: none
                          box-shadow: none
                      toolsets:
                        - toolset: toolset-trash
                          position: 
                           cx: 50
                           cy: 50
                          tools:
                            - type: 'usersvg'
                              position:
                                cx: 25
                                cy: 25
                                height: 45
                                width: 45
                              style: 'images'
                              images:
                                - default: /local/images/pmd.svg
                              styles:
                                usersvg:
                                  filter: invert(1)
                            - type: text
                              position:
                                cx: 10
                                cy: 80
                              text: 'PMD'
                              styles:
                                text:
                                  text-anchor: start
                                  font-size: 14em
                                  font-weight: 500
                            - type: state
                              position:
                                cx: 10
                                cy: 92
                              entity_index: 0
                              styles:
                                state:
                                  text-anchor: start
                                  font-size: 7em
                                  opacity: 0.5
```

### Expected behavior
Can't make invert work since it inverts twice because of the double svg overtop one another.

### Screenshots
'normally loaded'
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/2add380e-4ca2-414a-945d-b378bd63cbc1)

disabled 1 of the filters via inspector:
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/58057057-b7ae-4170-89c0-c217846821ef)

Completely deleting the 2nd SVG still shows the SVG in the card, here disabling the filter doesn't do anything:
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/d27f4a5c-4cca-4ede-80ce-f91b79bc5071)
