### ISSUE TITLE
SVG displaying problem with Firefox (after last udpate)

### ISSUE THREAD

**Issue by grichka49** [AmoebeLabs/swiss-army-knife-card#215]
## Bug report notice
SVG are cropped in Firefox. It seems to be OK with Chrome
Animation (animated SVG) are not smooth. I seems to be OK with Chrome

- [X ] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
The problem appears with last update v2.4.4
All was functional before update.

## Bug description
Some part of SVG are not displayed

### To Reproduce
Display the card with Firefox browser

### Screenshots
Firefox
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/31791870/c983d3c5-921b-4bfd-afc0-2efcf7230af0)

Chrome
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/31791870/9426e296-80fb-4839-9697-62b88feecee8)

### Desktop browser (please complete the following information):
 - OS: Windows 11
 -  Firefox 113.0.1

**Comment by AmoebeLabs** [comment]
Try disabling SVG injection:
```yaml
  options:
    svginjection: false     # true (default) for injection,
                            # false for keeping the external file
```
see: https://swiss-army-knife-card-manual.amoebelabs.com/tools/usersvg-tool/#styling-injected-vs-external-svgs

I will check firefox to see if I can find the problem FF has with injected SVGs.

**Comment by jwaz73** [comment]
I'm having the same issue with FF (v113.0.1) on Windows 11.  No issues with Chrome or Edge.

Where does the codeblock for disabling svgingection go?  I tried it here with no change:
```
      - type: usersvg
      ...
        styles:
          usersvg:
            options:
              svginjection: false

```

**Comment by AmoebeLabs** [comment]
> I'm having the same issue with FF (v113.0.1) on Windows 11. No issues with Chrome or Edge.
> 
> Where does the codeblock for disabling svgingection go? I tried it here with no change:
> 
> ```
>       - type: usersvg
>       ...
>         styles:
>           usersvg:
>             options:
>               svginjection: false
> ```

On the same level as the styles.
So:
```yaml
  - type:
    options:
      svginjection: false
    styles:
```
