### ISSUE TITLE
Impossible to change opacity of 'uom' through animations.

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#217]
## Swiss Army Knife version
2.4.4

## Bug description
Impossible to change opacity of 'uom' through animations. maybe other styles too? 

### To Reproduce

tested on 2 different cards/entities/... 
state works but uom doesn't
```

                        - type: state
                          position:
                            cx: 10
                            cy: 92
                          styles:
                            state:
                              text-anchor: start
                              font-size: 9em
                            uom:
                              opacity: 1 # it is possible to style it here, but not in the animations
                          entity_indexes:
                            - entity_index: 1
                            - entity_index: 0
                          user_actions:
                            tap_action:
                              haptic: success
                              actions:
                                - action: more-info
                          animations:
                            - state: 'on'
                              entity_index: 0
                              styles:
                                state:
                                  opacity: 0.8
                                  transition: opacity 0.5s linear
                                uom:
                                  opacity: 0.8
                                  transition: opacity 0.5s linear
                            - state: 'off'
                              entity_index: 0
                              styles:
                                state:
                                  opacity: 0
                                  transition: opacity 0.5s linear
                                uom:
                                  opacity: 0
                                  transition: opacity 0.5s linear
```
### Expected behavior
for the uom to follow the state animation

### Screenshots
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/3ebc0da0-86ca-491c-8d89-da3921dc3fd1)
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/5053bea1-fef7-42c6-bdc1-2a337ff81709)

**Comment by AmoebeLabs** [comment]
I’ll check uom, but in the mean time, try the following:
```yaml
                          animations:
                            - state: 'on'
                              entity_index: 0
                              styles:
                                tool:
                                  opacity: 0.8
                                  transition: opacity 0.5s linear
                            - state: 'off'
                              entity_index: 0
                              styles:
                                tool:
                                  opacity: 0
                                  transition: opacity 0.5s linear
```
