### ISSUE TITLE
Fix tool styling for all tools

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#221]
## Bug report notice
**Before** you file a bug, make sure that you did not make a configuration mistake. The Swiss Army Knife in its current state does not yet have full configuration sanity checks!

So make sure your problem is not related to that!
- [x] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
v2.4.4

## Bug description
See:
- #217 

But it seems like more tools have a broken styleMap for the tools part, so check all tools for this!

### Expected behavior

Working for state, tool says: display: none

![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/402dea6a-e573-4b56-ae2d-13ca75dbb26a)

uom, display: none
This is weird, because according to #217, uom styling is not honored. So, how come this works?
In different check with secondary entity as on/off, uom keeps at opacity 1...

But it is fixed now 🥳 

![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/889b6be0-7d0c-4dd5-a32d-7eab3a93b7cb)

state, display: none (styling gone, so uom displayed to left)
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/e9fcbd8a-9dad-4cab-b991-5a5816a2a3a0)

All normal again:
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/7996307/abc715b3-aeea-4094-8883-4c2a8b81b7d6)

### Desktop browser (please complete the following information):
 - OS: [e.g. Windows]
 - Version [e.g. 110]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [e.g. iPhone16]
 - OS: [e.g. iOS16]
 - Version [e.g. 16]

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.

**Comment by stinobook** [comment]
Hello, was just too late to report this for 2.4.5. just updated and tested if this fix fixed it but it didnt. 
usersvg styling through animations is also not working.
if i apply the filter as a main style it works, but not through animations. 

```
                        - type: usersvg
                          position:
                            cx: 75
                            cy: 15
                            height: 30
                            width: 30
                          entity_index: 1
                          styles:
                            usersvg:
                              filter: invert(50%) sepia(17%) saturate(5187%) hue-rotate(321deg) brightness(94%) contrast(89%)
                          style: 'images'
                          images:
                            - default: /local/images/main-brush.png
                          animations:
                            - state: 10
                              operator: <=
                              styles:
                                usersvg:
                                  filter: invert(50%) sepia(17%) saturate(5187%) hue-rotate(321deg) brightness(94%) contrast(89%)
                            - state: 10
                              operator: >
                              styles:
                                usersvg:
                                  filter: unset
```
