### ISSUE TITLE
2.4.5 somehow added .hidden class to usersvg.

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#224]
## Bug description
Since the 2.4.5 update i have one card where the usersvg somehow gets the .hidden class. Nothing of the code has been changed since 2.4.4.

### To Reproduce

Card code:
```

              - type: 'custom:swiss-army-knife-card'
                aspectratio: 1/1
                entities:
                  - entity: input_select.person_status_maddie
                  - entity: input_text.person_status_maddie
                layout:
                  styles:
                    card:
                      overflow: visible
                      background: transparent
                      border: none
                      box-shadow: none
                  toolsets:
                    - toolset: card
                      position:
                       cx: 50
                       cy: 50
                      tools:
                        - type: usersvg
                          position:
                            cx: 50
                            cy: 50
                            height: 100
                            width: 100
                          style: 'images'
                          images:
                            - default: /a....
                          clip_path:
                            position:
                              cx: 50
                              cy: 50
                              height: 100
                              width: 100
                              radius:
                                all: 5
```

### Screenshots
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/f25dd555-67e7-45ee-95cc-1a2138f38c93)

Same card/code on 2.4.4 version:
![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/51697064/4c5d3b7c-8488-467c-9dd8-710f5575ae6a)
