### ISSUE TITLE
iPhone Custom Element Doesn't exist

### ISSUE THREAD

**Issue by jn3va** [AmoebeLabs/swiss-army-knife-card#228]
I have an iPhone XR with iOS 15.5
The latest HomeAssistant mobile app
I'm using the latest SAK from HACS v2.4.6
Home Assistant is 2023.4.4

```
lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    sak-examples:
      mode: yaml
      title: Swiss Army Knife Examples
      icon: mdi:hospital-box
      show_in_sidebar: true
      filename: sak-examples-dashboard.yaml
```

I was able to get the examples to run on Chrome and Edge on Windows and also on a Fire Tablet running Fully Kiosk browser

The iPhone is the only endpoint that will not work. 

In sak-examples-dashboard.yaml I've commented out all of the views except sake7

When the dashboard loads on the iPhone I briefly see the title flash up 
Swiss Army Knife Examples 
and then get an error:
**Custom element doesn't exist: swiss-army-knife-card**

![Screenshot-iPhone](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/34897786/e81f4b40-f590-4059-b41f-73f244d2f7d7)

I also tried this with views 5 and 9 (sake5.yml and sake9.yml) with the same result.  The boards will display on all devices but the iPhone

I've tried clearing the iPhone app cache by off-loading and re-installing the HomeAssistant app.
I've also tried clearing the safari browser cache
restarting home assistant several times

The declutter card seems to load (no errors and its listed above the SAK-card in the sake7.yml) as well as other custom cards (e.g. custom-button apex etc.) with no issues

Anyone else seen this and have any solutions to try?
