### ISSUE TITLE
Live Update of Entities

### ISSUE THREAD

**Issue by martydingo** [AmoebeLabs/swiss-army-knife-card#229]
Hiya there,

This is a lovely tool, thanks very much! 

I would like to have the ability for cards to live update based on their states. 

As of currently, I have a card set up with the following animation:

```yaml
                - type: "circle"
                  entity_index: 0
                  position:
                    cx: 150
                    cy: 90
                    radius: 47
                  styles:
                    circle:
                      stroke: "var(--secondary-background-color)"
                      filter: url(#sak-nm-default)
                  animations:
                    - state: "[[[ return (state); ]]]"
                      styles:
                        circle:
                          filter: url(#nm-1-reverse)
                          fill: >-
                            [[[ return
                            `rgb(${states["light.office_door_spotlight"].attributes.rgb_color})`
                            ]]]
                    - state: "off"
                      styles:
                        circle:
                          filter: url(#sak-nm-default)
```

This card does change color based on the light, however upon updating the color on the same card, on a different tool (but within the same toolset), the card does not update the new light color on the card itself.
