### ISSUE TITLE
Add configuration to units of measurement state

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#24]
## The Problem To Be Solved
The units of measurement are always added/shown next to the state value.
In some cases this is not desired: the uoms should either not be displayed, or above or below the state.

Makes this a configuration 'show' option, where default = the old situation.

## (Optional): Suggested Solution
uom positioning:
```yaml
show:
  uom: default
  uom: above
  uom: below
  uom: none
```
