### ISSUE TITLE
scaling not working on mobile (android)

### ISSUE THREAD

**Issue by mrgrlscz** [AmoebeLabs/swiss-army-knife-card#245]
## Bug description
When introducing scaling at a toolset level, card do not display the same way on mobile (android app 2023.9.2-full) and desktop.

### To Reproduce
```
title: test1254
path: test1254
panel: false
cards:
  - type: 'custom:swiss-army-knife-card'
    layout:
      toolsets:
        - toolset: test1254
          position:
            cx: 50
            cy: 50
            scale: .6
          tools:
            - type: rectangle
              id: 0
              position:
                cx: 50
                cy: 50
                width: 50
                height: 50
              styles:
                rectangle:
                  fill: red
```
Desktop:

![WhatsApp Image 2023-10-11 à 00 21 28](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/113037215/885f293e-bd57-4d7a-9cc9-c13d737cebef)
Mobile:
![WhatsApp Image 2023-10-11 à 00 21 13](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/113037215/ab2c019f-6616-400e-bea7-59efde4e7eb0)

### Expected behavior
Just the card looking exactly the same on mobile AND desktop

### Screenshots
Desktop:
![WhatsApp Image 2023-10-11 à 00 03 56](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/113037215/6ed19939-2e94-4580-8b46-53ce47e5cf3e)
Mobile:
![WhatsApp Image 2023-10-11 à 00 02 56](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/113037215/933aa7ee-93b4-47b9-bacc-9aff14149d5a)

### Desktop browser (please complete the following information):
 - OS: win10
 - Browser: Chrome 
 - Version: 117.0.5938.150

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: xiaomi 9t
 - OS: android 11
 - Browser: chrome
