### ISSUE TITLE
the ">" and ">=" operator gets ignored

### ISSUE THREAD

**Issue by tuupos** [AmoebeLabs/swiss-army-knife-card#246]
So make sure your problem is not related to that!
- [ X] Yes, I'm sure that it is not a configuration mistake

## Swiss Army Knife version
v2.5.1-dev.2

## Bug description
When I use the the ">" and ">=" operator in my yaml it gets ignored beacuse it thinks it's part of scripting. 

```
- state: '2000'
  operator: >
  styles:
    icon:
      animation: spin 3s linear infinite
      fill: var(--theme-sys-color-secondary)
      opacity: 0.9
```

e.g. like the > sign after the next fill.

```
 fill: >
 [[[ if (['home', 'not_home'].includes(state)) return 'var(--theme-sys-color-primary)';
                          return 'var(--theme-sys-color-tertiary)';
```

### Expected behavior
The > sign should be seen as "greater than" and not as the beginning of a multiline code.

![image](https://github.com/AmoebeLabs/swiss-army-knife-card/assets/54961501/e3c55bfa-823f-410e-849e-5df1d4061b89)

**Comment by jwaz73** [comment]
@tuupos Just in case you have not found a solution to this yet...

I had to spend some time on the animation operators to understand their behavior.  I found passing the operators as text corrected the strange results I was getting (enclose the operators in single quotes).
```
                    - state: 'P4'
                      operator: '!='
                      styles:
                        text:
                          fill: var(--theme-sys-palette-secondary85)
```

In the documentation for [Supported Operators](https://swiss-army-knife-card-manual.amoebelabs.com/basics/animations/state-operators/#supported-operators) Marco does call out that all values should be passed as strings.  The examples on the page do not show this for the operators but I tried it and achieved the results i was looking for.

Happy New Year!

-James
