### ISSUE TITLE
Feature: Refresh SVG on animation/time/state/...

### ISSUE THREAD

**Issue by stinobook** [AmoebeLabs/swiss-army-knife-card#249]
## The Problem To Be Solved
usersvg images are loaded on card load, not on image load.

### Additional background:
trying to implement a camera(image stream, not camera stream) view inside the card. 

A concise description of your preferred solution. Things to address include:

I have written a derived entity so that my 'state' always updates every few seconds.
It switches between 2 states, and i have 2 images 'coupled' to it.

## (Optional): Suggested Solution
how i see it now the images are 'preloaded' by the card as soon as the card is loaded, but if we can just load the image when it is requested instead of on card load this would make it update each time and allow us to insert a stream inside the card.

my tool: 

```
                - type: usersvg
                  position:
                    cx: 50
                    cy: 55
                    height: 35
                    width: 50
                  style: 'images'
                  entity_index: 12
                  derived_entity:
                    input : '[[[ return state ]]]'
                    state: >
                      [[[
                        if (typeof(entity) === 'undefined') return;
                        if (typeof(state) === 'undefined') return;
                        if (state === 'undefined') return;
                        var sec = state.slice(-1);
                        if (sec % 2 == 0) {
                            return ('even');
                        } else {
                            return ('uneven');
                        }
                  images:
                    - default: /api/image_proxy/image.----
                    - even: /api/image_proxy/image.----
                    - uneven: /api/image_proxy/image.----
                  animations:
                    - state: 'even'
                      image: even
                    - state: 'uneven'
                      image: uneven`


```

**Comment by kkggaa45** [comment]
Hi, try this example (this is how I output the video stream from the camera and album covers from the media player)
```
            ####################################################
                  - type: usersvg
                    position:
                      cx: 50
                      cy: 38
                      height: 73
                      width: 97
                    clip_path:
                        position:
                          cx: 50
                          cy: 50      
                          height: 73  
                          width: 97
                          radius:    
                            top_left: 1.2
                            top_right: 1.2
                            bottom_right: 1.2
                            bottom_left: 1.2
                    entity_index: 0
                    style: 'images'
                    images: 
                      - default: >
                          [[[
                            {
                              return (entity_config?.entity_picture ||
                                     entity.attributes?.entity_picture || 'none');
                            }
                          ]]]
            ####################################################

```

**Comment by stinobook** [comment]
Does that update for you without refreshing the page? it just loads a static image which was also my issue.

**Comment by kkggaa45** [comment]
Example of video stream output from a camera
`      - type: 'custom:swiss-army-knife-card'
        entities:
            - entity: camera.cam051
        layout:
            aspectratio: 1/.58
            toolsets:
              - toolset: video
                position:
                  cx: 50
                  cy: 50
                tools:
            ####################################################
                  - type: rectex
                    entity_index: 0
                    position:
                      cx: 50
                      cy: 29
                      width: 99
                      height: 57
                      radius:
                        top_left: 1.5
                        top_right: 1.5
                        bottom_right: 1.5
                        bottom_left: 1.5
                    styles:
                        rectex:
                            stroke-width: 0.7em       # width of stroke. 0 = no stroke.
                            stroke: '#909090'
                            fill: '#363636'
        
            ####################################################
                  - type: usersvg
                    position:
                      cx: 50
                      cy: 29
                      height: 55
                      width: 97
                    clip_path:
                        position:
                          cx: 50
                          cy: 50      
                          height: 55  
                          width: 97
                          radius:    
                            top_left: 1.3
                            top_right: 1.3
                            bottom_right: 1.3
                            bottom_left: 1.3
                    entity_index: 0
                    style: 'images'
                    images: 
                      - default: >
                          [[[
                            {
                              return (entity_config?.entity_picture ||
                                     entity.attributes?.entity_picture || 'none');
                            }
                          ]]]
            ####################################################
                  - type: rectex
                    entity_index: 0
                    position:
                      cx: 50
                      cy: 38
                      width: 100
                      height: 76
                      radius:
                        top_left: 0
                        top_right: 0
                        bottom_right: 0
                        bottom_left: 0
                    styles:
                      rectex:
                        stroke: var(--primary-background-color)
                        opacity: 0
`

**Comment by kkggaa45** [comment]
Example of video stream output from a camera

      - type: 'custom:swiss-army-knife-card'
        entities:
            - entity: camera.cam051
        layout:
            aspectratio: 1/.58
            toolsets:
              - toolset: video
                position:
                  cx: 50
                  cy: 50
                tools:
            ####################################################
                  - type: rectex
                    entity_index: 0
                    position:
                      cx: 50
                      cy: 29
                      width: 99
                      height: 57
                      radius:
                        top_left: 1.5
                        top_right: 1.5
                        bottom_right: 1.5
                        bottom_left: 1.5
                    styles:
                        rectex:
                            stroke-width: 0.7em       # width of stroke. 0 = no stroke.
                            stroke: '#909090'
                            fill: '#363636'
        
            ####################################################
                  - type: usersvg
                    position:
                      cx: 50
                      cy: 29
                      height: 55
                      width: 97
                    clip_path:
                        position:
                          cx: 50
                          cy: 50      
                          height: 55  
                          width: 97
                          radius:    
                            top_left: 1.3
                            top_right: 1.3
                            bottom_right: 1.3
                            bottom_left: 1.3
                    entity_index: 0
                    style: 'images'
                    images: 
                      - default: >
                          [[[
                            {
                              return (entity_config?.entity_picture ||
                                     entity.attributes?.entity_picture || 'none');
                            }
                          ]]]
            ####################################################

**Comment by stinobook** [comment]
Yes I got it working from your previous comment but that would give me a static image on the SAK card instead of a live view of the camera. Is it the same for you or do you have in fact a live updating feed ?

**Comment by kkggaa45** [comment]
something like this
[https://youtube.com/shorts/HemeLBO-lEI?feature=share](url)

**Comment by stinobook** [comment]
For me it doesn't update the card like with you?
```

          - entity: camera.p1s_...._camera


                - type: usersvg
                  position:
                    cx: 50
                    cy: 50
                    height: 50
                    width: 50
                  clip_path:
                    position:
                      cx: 50
                      cy: 50
                      height: 73
                      width: 97
                      radius:
                        top_left: 1.2
                        top_right: 1.2
                        bottom_right: 1.2
                        bottom_left: 1.2
                  entity_index: 15
                  style: "images"
                  images:
                    - default: >
                        [[[
                          {
                            return (entity_config?.entity_picture ||
                                    entity.attributes?.entity_picture || 'none');
                          }
                        ]]]

```
https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYNuRv9XQr4_6O1P5xvrGESC7Mf0ATNW8wWClQoJDZY8bx9nmVpxYxU3%2F%24%7Bf%7D%3Fo%3DAh_CWlESYb6jmRiB2gSSjsmDFY3VjsQNkRQvEmQP7Re4%26v%3D1%26x%3D3%26a%3DCAog7VaV9C9x0yg3fIYf75PTdZLXBVPAs3bLsRZGRk7zlVoSbRCY1u_jzDIYmObqt9YyIgEAUgSC7Mf0WgRxYxU3aiZjrdZJP62CVYD9EhVfxZVsz2t5EZ0a4gzztHVkOHlP5JYyfs656HImz1OSrZpupLnLjN1qeqwVMhAPHPy6LV7OT_YDE7IHabTwTzhNqT8%26e%3D1741189460%26fl%3D%26r%3D5AD6BB8E-5511-40F4-8D55-4316A7895A1C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.clouddocs%26ckz%3Dcom.apple.CloudDocs%26p%3D109%26s%3DbOdorSq2ThUMJyl3-DKWoOLHdxk&uk=qvZCaLRU9gXkXVJaSfv8bw&f=Screen%20Recording%202025-02-03%20at%2016.43.23.mov&sz=4626896
