### ISSUE TITLE
Split styles section into tool parts

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#25]
## The Problem To Be Solved
Every tool can be styled using the `styles` section.
The segmented arc uses two sections:
- `styles` for the segmented arc itself
- `styles_bg` for the background of the arc

Other tools also will need multiple styles sections to be able to style each part. Some tools already have multiple subsections for styles, so need not to be changed.

Using a zillion style_** sections is not an option.

This must be implemented for all tools. Lot of work, as the yaml views/templates must be changed also:
- [x] Area
- [x] Badge
- [x] Bar
- [x] Circle
- [x] Horseshoe
- [x] Icon
- [x] Ellipse
- [x] Line
- [x] Name
- [x] Rectangle
- [x] RectEx
- [x] SegmentedArc
- [x] Slider
- [x] State
- [x] UserSvg

## (Optional): Suggested Solution
The general proposed solution is to make the `styles` section a map of styling parts. Easy to extent & process.

```yaml
styles:
  front:
    fill: red;
  background:
    fill: black;
```
but also:
```yaml
styles:
  bar:
    fill: red;
  label_min:
    fill: black;
  label_max:
    fill: black;
```
