### ISSUE TITLE
Refactor Icon and font size to use %

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#32]
## The Problem To Be Solved
Both font-size and icon-size is currently not consistent with the percentages used for all the other tools.

To make matters worse, some css is also specifying font-sizes, sometimes % font sizes. This results in inconsistent yaml specifications.

For instance:
![image](https://user-images.githubusercontent.com/7996307/101208503-92ae4c00-3672-11eb-9d13-83a710d800ed.png)

The font-size for the Name is larger than for the Area, however in the yaml spec this is the opposite:
```yaml
      # Name of entity
      - type: name
        cx: 5
        cy: 81
        id: 4
        entity_index: '[[entity_light]]'
        styles:
          name:
            font-size: 1.8em
            font-weight: 700
            text-anchor: start

      # Area of entity
      - type: area
        entity_index: 0
        id: 5
        cx: 5
        cy: 91
        styles:
          area:
            font-size: 2.4em
            text-anchor: start
```
This is caused by css definitions!

## (Optional): Suggested Solution
It is not very difficult, but takes some time to change all the yaml definitions & code:
- remove css definitions for font-size in at least the `entity__name` and `entity__area` definitions
- use a relative font-size of 1em for 1%, ie size is consistent with other tools. This means that with the current svg dimensions (400x400), a value of 1em equals 4px! the ::host font-size must be set to this value!
- change all yaml definitions for font-size and icon-size
