### ISSUE TITLE
Add regular (convex/star) polygon tool

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#34]
## The Problem To Be Solved
Add generic polygon tool. This tool can generate multiple kinds of polygons (regular ones!) using Schläfli symbol to describe and generate the regular polygons:
- convex polygons
- star polygons

## (Optional): Suggested Solution
These are the possible figures made by Ana Tudor (https://codepen.io/thebabydino/pen/WbjdRq):

![image](https://user-images.githubusercontent.com/7996307/101262360-695af200-373e-11eb-8caa-27ab14532291.png)

Integrate the function into a tool class, and ready!

### First simple result:
![image](https://user-images.githubusercontent.com/7996307/101262468-4715a400-373f-11eb-867c-f9012f1335c0.png)

Using this yaml definition:
```yaml
          layout:
            toolsets:
              - toolset: polytest
                position:
                  cx: 100
                  cy: 50
                tools:
                  - type: regpoly
                    cx: 0
                    cy: 50
                    radius: 45
                    side_count: 6
                    side_skip: 1
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        transform: skewX(30deg)

                  - type: regpoly
                    cx: 0
                    cy: 50
                    radius: 35
                    side_count: 6
                    side_skip: 1
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        fill: gray
                        stroke: gray
                        opacity: 0.05
                        filter: url(#nm-2)

                  - type: regpoly
                    cx: 0
                    cy: 50
                    radius: 25
                    side_count: 6
                    side_skip: 1
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.9
                        filter: url(#nm-2)

                  - type: regpoly
                    cx: 0
                    cy: 50
                    radius: 15
                    side_count: 18
                    side_skip: 6
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.5
                        filter: url(#nm-2)

####
                  - type: regpoly
                    cx: 100
                    cy: 50
                    radius: 45
                    side_count: 6
                    side_skip: 1
                    styles:
                      regpoly:
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)

                  - type: regpoly
                    cx: 100
                    cy: 50
                    radius: 45
                    side_count: 6
                    side_skip: 2
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.3
                        filter: url(#nm-2)

                  - type: regpoly
                    cx: 100
                    cy: 50
                    radius: 35
                    side_count: 6
                    side_skip: 2
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.3
                        filter: url(#nm-2)

                  - type: regpoly
                    cx: 100
                    cy: 50
                    radius: 25
                    side_count: 6
                    side_skip: 2
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.3
                        # filter: url(#nm-1-reverse)
                        filter: url(#nm-2)

                  - type: regpoly
                    cx: 100
                    cy: 50
                    radius: 15
                    side_count: 6
                    side_skip: 2
                    styles:
                      regpoly:
                        fill-rule: nonzero
                        fill: var(--primary-background-color)
                        stroke: var(--primary-background-color)
                        opacity: 0.3
                        filter: url(#nm-2)

```
