### ISSUE TITLE
Refactor tool position & dimensions configuration

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#39]
## The Problem To Be Solved
There is currently a discrepancy between the toolset and tool configuration.
The toolset specifies a separate position map with position & dimensions, where the tool uses inline configuration.

Refactor this to use the position map for tools too.
- easier for the eye
- easier to document

## (Optional): Suggested Solution
Easy peasy:
```yaml
  - tool: some example
    type: circle
    position:
      cx: 50
      cy: 40
      radius: 45
```
Instead of:
```yaml
  - tool: some example
    type: circle
    cx: 50
    cy: 40
    radius: 45
```
