### ISSUE TITLE
Support more than one entity_index in animations section

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#47]
## The Problem To Be Solved
The current animations handling assumes the current entity_index as the state that is processed for getting different animations/styles per state.

In some situations it is very handy if another entity's state can overrule/adjust the styling/animations of the current entity tool.

Examples:
- Disable tool depending on state on/off of another entity
- Hide tool/toolset depending on state undefined/other of another entity

## (Optional): Suggested Solution
Adding an optional `entity_index:` to the animations is enough. 

**Note:**
Must check the `reuse` flag. TThat flag takes care of re-using the current/previous state, but was made assuming there is only ONE animation that can determine the styling, which is not true anymore if more than one entity_index can format the styling.

So should the extra state be able to:
- overwrite/replace the current animation styling (it is a list, so there can already be a styling)
- always merge the styles, ie reuse-current.

Current for entity_index = 0:
```yaml
animations:
  - state: 'on'
    styles:
      circle:
        fill: darkorange
        transition: 'all .8s ease'
  - state: 'off'
    styles:
      circle:
        fill: lightgray
        transition: 'all .8s ease'
```

Extend with:
- in 'off' state for entity_index: 1, the on/off states for entity_index: 0 are still applied, ie they change fill color, but can't be clicked on, as pointer-events are disabled. Furthermore, opacity is set to 0.1
- in 'on' state for entity_index 1, the tool is enabled again for input

```yaml
animations:
  - state: 'on'
    styles:
      circle:
        fill: darkorange
        transition: 'all .8s ease'
  - state: 'off'
    styles:
      circle:
        fill: lightgray
        transition: 'all .8s ease'

  - state: 'on'
    entity_index: 1
    reuse: true
    styles:
      circle:
        opacity: 1
        pointer-events: auto

  - state: 'off'
    entity_index: 1
    reuse: true
    styles:
      circle:
        opacity: .1
        pointer-events: none
```
