### ISSUE TITLE
Add support for classes for easier and consistent styling

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#49]
## The Problem To Be Solved
The current static tool styling and animations sections use a `styles` section to define css and svg styles. This works ok.
However, one need to specify every single css style for each part, where css/html already defined classes to make this a lot easier.

So add this `classes` option to:
- define classes with true/false (a style map!!) in the classes section and animations section
- think about defining the classes in the sak template section, so any user can define its own classes/styles

### Add classes section to tool and animations:

```yaml
animations:
  - state: 'on'
    styles:
      circle:
        fill: darkorange
        transition: 'all .8s ease'
  - state: 'off'
    styles:
      circle:
        fill: lightgray
        transition: 'all .8s ease'
  - state: 'on'
    entity_index: 1
    reuse: true
    classes:
      circle:
        sak-enabled: true
        sak-disabled: false
  - state: 'off'
    entity_index: 1
    reuse: true
    classes:
      circle:
        sak-enabled: false
        sak-disabled: true
```

### Use lit-elements `styleMap` functionality
This one can enable (true) and disable (false) classes. That should be ease to add using some small code refactoring in the render methods.
The system /card classes get a `sak-` prefix, so no user can overwrite them...

### Add classes definitions in the template
So users can define there own classes. These are then added to the styles section.
That is also required for svg filters and other stuff. Not yet done!!!!

NOTE:
The `css_extra_definitions` section can also define `@keyframes` for defining own animations!

```yaml
css_extra_definitions:
  - descr: class for whatever
    content: |
      .whatever {
        fill: orange-01;
        stroke-width: 2;
        stroke: yellow;
        opacity: 0.2;
      }
      
  - descr: class for whoever
    content: |
      .whoever {
        color: green;
        align-text: middle;
      }
```

#### **IMPORTANT NOTE:**
And remember: (inline) styles overwrite the class specifications!!! ALWAYS!!!

This also means that the current inline styles for all tools should be moved to css, as otherwise the class definitions won't work, as they will be overwritten by the predefined inline styles!
