### ISSUE TITLE
Refactor: move actions/tap_action from card section to tool section

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#51]
## The Problem To Be Solved
The `tap_action` is currently defined under the entities section of the card. This works, but causes some problems for tools attached to these entities (using `entity_index: `), but wanting different actions when clicking the tool.

Currently this is solved by using the same entity more than once.

By moving the actions/tap_action to the tool, this problem disappears and makes it very explicit what action a tool results in.

### Move config to tools section, where one can define multiple tap_actions!:
```yaml
# ------------------------------------------------------------
- type: circle
  entity_index: 0
  #
  # Circle is used as button to switch light on/off
  #
  user_actions:
    tap_action:
      haptic: light
      actions:
        - action: call-service
          service: light.toggle
```
Climate example
```yaml
- type: slider
  entity_index: 1
  #
  # Slider only specifies tap_action in this case. Dragging
  # does not imply any action.
  #
  user_actions:
    tap_action:
      haptic: light
      actions:
        - action: call-service
          service: climate.set_temperature
          parameter: temperature
          service_data:
            # Override entity_id. Otherwise entity_index is used...
            entity_id: climate.calenta
```
Slider with both a click and a drag action.
Slider without a click action only responds to the dragging of the thumb.
```yaml
- type: slider
  entity_index: 0
  #
  # Slider is used to set brightness percentage
  #
  user_actions:
    drag_action:
      update_interval: 200
      haptic: selection
      actions:
        - action: call-service
          service: light.turn_on
          parameter: brightness_pct

    tap_action:
      haptic: light
      actions:
        - action: call-service
          service: light.turn_on
          parameter: brightness_pct
```

### Move click handlers from card context to basetool context
The most logical place when moving this to the tools.

The click handler should process the new config and fill the `service_data` with the right info depending on the specified `entity_index`, or `service_data`.
