### ISSUE TITLE
Add lines tool

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#55]
## The Problem To Be Solved
There is a simple `line` tool which can draw a single line. But what about a polyline, or using multiple lines as ONE tool? By supporting the svg `polyline`, it is easy to also support multiple lines as one object.

So add this tool and see what functionality can be added to this tool to make it nice:
- lines
- points
- multi part styling

## (Optional): Suggested Solution
If `lines` can be made of different parts, one could also style the parts differently. This makes the tool much more usable. However, what about `colorstop` etc.: they are not yet configured for multi-part tools, which should be if you want to do this. Animations do support multi-part tools already, so for now one should use those...

```yaml
- type: lines
  position:
    one:
      - line:
          cx: 50
          cy: 50
          length: 190
          orientation: horizontal
      - points:
          - x: 10
            y: 20
          - x: 20
            y: 30
    two:
      - points:
          - x: 200
            y: 200
          - x: 20
            y: 40
            close: true
  styles:
    one:
      stroke: lightgray
      stroke-opacity: 0.7
      stroke-width: 5
    two:
      stroke-opacity: 0.7
      stroke-width: 7
```
Colorstops should then support multiple parts.

And this format still doesn't make it possible to have different colors for fill and stroke for instance. The fill and stroke should go into the colorstops itself. Hmmmmmmm. Colorstops with styles and classes??
```yaml
  colorstops:
    one:
      fill: true
      colors:
        0: '#A8E05F'
        51: '#FDD74B'
        101: '#FE9B57'
        151: '#FE6A69'
        201: '#A97ABC'
        301: '#A87383'
```

So this way seems better if made consistent with animations, and styles/classes, a colorstop should be defined as follows:
```yaml
  colorstops:
    colors:
      - stop: 0                 # The stop
        styles:                 # Styles / Classes
          one:                  # The part
            fill: '#A8E05F'
            stroke: '#A8E05E'
      - stop: 51
        classes:
          one:
            myClass: true       #'#FDD74B'
      - stop: 101
        styles:
          one:
            fill: '#FE9B57'
      - stop: 151
        styles:
          one:
            fill: '#FE6A69'
      - stop: 201
        styles:
          one:
            fill: '#A97ABC'
      - stop: 301
        styles:
          one:
            fill: '#A87383'

```
In which case things like `stroke-width`, `opacity`, etc can also be specified!
