### ISSUE TITLE
Dark / Light theming implementation for colorstops/lists

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#69]
## The Problem To Be Solved
Home Assistant supports themes with separate dark and light settings. HA also responds to dark/light system settings using the `window.matchMedia('(prefers-color-scheme: dark)')` media query to switch themes.

All the theme CSS settings will therefore change automatically: nothing needs to be done by the card itself.

However: in some cases, when the card uses its own colorstops/lists, some of those colors might conflict with a dark or light color scheme: it would be nice if this can be adjusted to the current active mode of the theme!

### Additional background:
HA responds itself to the media query change, but can also override the dark/light setting manually.

Additionally, HA makes some of the themes settings & configuration available throught the `hass` property which is set using the `set hass()` function call.

The `hass` object has the following properties for themes:
```yaml
  themes:
    darkMode: true/false
    theme: <name of active theme>
    themes:
      - <name of active theme>
        modes:
          dark:
          light:
```

## (Optional): Suggested Solution

The change in mode seems to be notified directly using the `hass` object update, so any card can respond to this change and act upon that change.

If a colorstop/list would have the same implementation as a theme, ie a `modes` map with `light` and `dark` maps, the card can respond to the dark/light mode and adapt the colorstop/list accordingly.

Below a colorswatch example. Colorstop/list should be a bit different...

```yaml
color_swatch_rgb:
  template:
    type: colorswatch
  colorswatch:
    colorswatch: color_palette_default_gradient_white_orange
    colors:
      default:
        --sak-cs-default-text: 'var(--primary-text-color)'
        --sak-cs-default-background: 'var(--primary-background-color)'
      light:
        --sak-cs-default-01: 'darkred'
        --sak-cs-default-02: 'darkgreen'
        --sak-cs-default-03: 'darkblue'
      dark:
        --sak-cs-default-01: 'red'
        --sak-cs-default-02: 'green'
        --sak-cs-default-03: 'blue'
```

The colorstop/lists changes should change to support dark/light modes: #48 and #58
