### ISSUE TITLE
Add Card/Toolset styles/classes setting and dark/light selection

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#70]
## The Problem To Be Solved
Every tool can be styled upon a state change. However, it would be nice if one could change 'global' card styling upon a change.

For instance: the background color should be changed. This should be done on the `ha-card` level. Furthermore if the background changes from light to dark, the text colors should be reversed if possible. And it would be nice if we could use the dark theme settings for this for instance.

### Part 1
For styles/classes just add an extra map property:
```yaml
  styles:
    partx:
    party:
    card:
    toolset:
```
### Part 2

Furthermore to support settings from the dark theme to invert text colors, one could define this as follows:
```yaml
  styles:
    card:
      --primary-text-color: '[[[ return themes.themes[hass.themes.theme].modes.dark.primary-text-color; ]]]'
      # Shorter, better. Note that this requires this variable to be set in the dark part. Currently
      # some `theme-default...` variable is used, to have generic defines in the theme...
      --primary-text-color: '[[[ return theme.dark.primary-text-color; ]]]'
```

As noticed above: a theme must define these var's, which is not the case right now...

**Note @2022.01.28**
By using Material Design Colors WEB CSS variables style, there is no need to access the `theme` configuration.

MDC WEB defines so called '-on' colors:
- --primary-text-color-on-background
- --primary-text-color-on-primary
- --primary-text-color-on-secondary
- etc...

So, if you use the primary color for the card's background, one should use the primary-text-color-on-primary for the text and icons. One can redefine the --primary-text-color on the card level (style: card: ) to just change (temporarily) the used colors!

```yaml
  styles:
    card:
      background-color: var(--primary-color)
      --primary-text-color: var(--primary-text-color-on-primary)
```

CSS Vars are not exact!
