### ISSUE TITLE
Reorganize development environment

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#77]
## The Problem To Be Solved
Development is currently done in the most simple way: a single source file that is part of my Home Assistant configuration and edited directly.

If the source file is split up into multiple files, a build environment is required to create the distribution.

It also makes it important to have a remote docker development environment, so the card can be active at all times and used in my HA environment.

## (Optional): Suggested Solution
As mentioned on Discord by one of the developers: visual studio code remote containers now enable a fully remote environment: source files are also stored in the docker container, and vs code can still access these files:
- git can be managed from the container
- building can be managed from the container (and GitHub using GitHub actions)
- testing can be managed from the container: the custom card is available using the IP address and port number.

This was previously also possible, but with a lot of work. I could never get it to work, or had constant issues. Now it should work out of the box!

That will hopefully help me with more code quality issues, like issue #76. I would be nice to solve that problem...

**Comment by AmoebeLabs** [comment]
## Progress

Testing with container in host mode. No portmapping yet. This DOES work!!!!
```yaml
  dev-sak:
    container_name: dev-sak
    network_mode: host
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    command: /bin/sh -c "while sleep 60000; do :; done"
    volumes:
      - $DOCKERDIR/dev/sak/workspaces:/workspaces
      - $DOCKERDIR/dev/sak/vscode:/vscode
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

Use vscode to
- connect to server via remote SSH
- attach to container 'dev-sak' once connected via SSH
- define workspaces and everything seems right
