### ISSUE TITLE
Template without defaults/variables section doesn't work

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/swiss-army-knife-card#87]
## Bug description
Example can be found in `view-sake10.yml`:

```YAML
  - type: segarc
    id: 0
    entity_index: 1
    position:
      cx: 80
      cy: 25
      start_angle: 0
      end_angle: 360
      width: 2
      radius: 15
    scale:
      min: 0
      max: 100
    show:
      scale: false
      style: 'colorlist'
    derived_entity:
      template:
        name: derived_entity_brightness
        # BUG:
        # Do need a variable section here and defaults in
        # template itself. That should not be the case...
        #
        # A template without variables SHOULD be possible...
        variables:
          - dummyvar: 'bug'
    segments:
      colorlist:
        gap: 1
        colors:
          - 'var(--primary-text-color)'
    animation:
      duration: 5
    styles:
      foreground:
        fill: var(--primary-text-color)
      background:
        fill: var(--cs-theme-default-darken-15)

```

### Expected behavior
A template without variables SHOULD be possible.

The workaround is defining a dummyvar :smile:

### Desktop browser (please complete the following information):
 - OS: [e.g. Windows]
 - Version [e.g. 110]

### Companion App on Smartphone/Tablet (please complete the following information):
 - Device: [e.g. iPhone16]
 - OS: [e.g. iOS16]
 - Version [e.g. 16]

**Additional context**

## (Optional): Suggested Solution
Any suggested solution to this bug.
